name: lint-review
on:
  pull_request:

jobs:
  lint_review:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Run Verible action
        uses: chipsalliance/verible-linter-action@main
        with:
          paths:
            ./tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          suggest_fixes: 'false'
